# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cantidad_comprada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
